### ISSUE TITLE
Executing contract methods

### ISSUE THREAD

**Issue by ClaireMao1996** [jemshit/WalletConnect#4]
Successfully connected Metamask with this library! Now, How do I establish web3 connection to my contract and call the contract's method. Can you please provide me some examples?

**Comment by jemshit** [comment]
[This is](https://github.com/jemshit/WalletConnect/blob/c00c9481a9ce872c8376a0efd7bd2fd7816ef4b5/sample/src/main/java/walletconnect/sample/DAppFragment.kt#L356) example of calling  [transfer method of smart contract](https://bscscan.com/address/0xb465f3cb6Aba6eE375E12918387DE1eaC2301B05#writeContract#F8) of BEP-20 token, which has parameters `to`, `amount`. Sample code has comments explaining.

But for more information on how to call any function of smart contract you [have to dig this](https://docs.soliditylang.org/en/latest/abi-spec.html).

**Comment by ClaireMao1996** [comment]
Thanks for the answer, by the way can it expose the method `eth_signTypedData_v4`? Currently I only find `eth_signTypedData`
https://docs.metamask.io/guide/signing-data.html#a-brief-history
