### ISSUE TITLE
Sigin Request fail

### ISSUE THREAD

**Issue by AndroidCrazyBoy** [jemshit/WalletConnect#5]
sigin request fail ,because BaseFragment#approvedAddress is null

**Comment by jemshit** [comment]
Need detail

**Comment by AndroidCrazyBoy** [comment]
> Need detail

App click 'Open',  show connected, but click 'Sign Request' no response,  because BaseFragment#approvedAddress is null

**Comment by AndroidCrazyBoy** [comment]
![WX20230111-164917](https://user-images.githubusercontent.com/7986659/211760353-fc8a1fb5-9c7b-4a0a-bde8-8b9128f75b5a.png)

**Comment by jemshit** [comment]
1) dApp: Open
2) Wallet: Open
3) dApp: SessionRequest
4) Wallet: Accept SR
5) dApp: SignRequest

**Comment by AndroidCrazyBoy** [comment]
oo, thank you
